mainUrl: "./md/index.md"
navigation:
  - label: "Home"
    file: "./md/index.md"
  - label: "Overview"
    file: "./md/overview.md"
  - label: "Docs"
    children:
      - label: "Configuration"
        file: "./md/configuration.md"
      - label: "Markdown syntax"
        file: "./md/syntax.md"
      - label: "Anchors"
        file: "./md/anchors.md"
